### ISSUE TITLE
Panic during startup

### ISSUE THREAD

**Issue by ronnygunawan** [TokoBapak/mock-payment-provider#27]
```
2023-06-12 12:23:33 goroutine 1 [running]:
2023-06-12 12:23:33 github.com/go-chi/chi/v5.(*Mux).Use(...)
2023-06-12 12:23:33     /go/pkg/mod/github.com/go-chi/chi/v5@v5.0.8/mux.go:102
2023-06-12 12:23:33 mock-payment-provider/presentation.NewPresenter({{0xc00001c026, 0x7}, {0xc00002000a, 0x4}, {0xc00001e00b, 0xf}, 0xc000022180})
2023-06-12 12:23:33     /app/presentation/presentation.go:53 +0x9a6
2023-06-12 12:23:33 main.main()
2023-06-12 12:23:33     /app/main.go:82 +0xa8d
2023-06-12 12:23:40 panic: chi: all middlewares must be defined before routes on a mux
```

**Comment by aldy505** [comment]
Released https://github.com/TokoBapak/mock-payment-provider/pkgs/container/mock-payment-provider/102353199?tag=sha-6395d75
